project_id = "qvhthjtdzeerafabfbfc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
# port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
# refresh_token_rotation_enabled = true
# security_update_password_require_reauthentication = true

[functions.ai-chat-booking]
verify_jwt = false

[functions.openai-realtime-voice]
verify_jwt = false

[functions.create-staff-account]
verify_jwt = false

[functions.update-staff-role]
verify_jwt = false