-- Migration to create the unified notification system
-- Date: 2026-03-06

-- 1. Create Enums
DO $$ BEGIN
    CREATE TYPE public.notification_type AS ENUM (
        'service_request', 'table_reservation', 'spa_booking', 'message', 'system', 'event', 'feedback'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.notification_channel AS ENUM (
        'in_app', 'email', 'push', 'sms'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.recipient_type AS ENUM (
        'guest', 'staff', 'manager', 'system'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.notification_status AS ENUM (
        'pending', 'sent', 'delivered', 'failed', 'read', 'cancelled'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.notification_priority AS ENUM (
        'low', 'normal', 'high', 'critical'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Create Notifications Table
CREATE TABLE IF NOT EXISTS public.notifications (
    notification_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hotel_id UUID REFERENCES public.hotels(id) ON DELETE CASCADE,
    type public.notification_type NOT NULL,
    channel public.notification_channel NOT NULL DEFAULT 'in_app',
    recipient_type public.recipient_type NOT NULL,
    recipient_id UUID NOT NULL, -- FK to Guest (guest_id) or Staff (auth.users.id) depending on recipient_type
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    status public.notification_status NOT NULL DEFAULT 'pending',
    priority public.notification_priority NOT NULL DEFAULT 'normal',
    source_module TEXT,
    source_event TEXT,
    reference_id UUID,
    reference_type TEXT,
    scheduled_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    read_at TIMESTAMPTZ,
    retry_count INTEGER DEFAULT 0,
    error_message TEXT,
    idempotency_key TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by TEXT DEFAULT 'system'
);

-- 3. Add Indices
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON public.notifications (recipient_id, recipient_type);
CREATE INDEX IF NOT EXISTS idx_notifications_status ON public.notifications (status);
CREATE INDEX IF NOT EXISTS idx_notifications_hotel ON public.notifications (hotel_id);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications (created_at DESC);

-- 4. Idempotency Key Trigger (Optional helper)
-- Usually generated by app, but we can have a fallback
CREATE OR REPLACE FUNCTION public.generate_notification_idempotency_key()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.idempotency_key IS NULL THEN
        NEW.idempotency_key := encode(digest(
            concat(
                NEW.type::text, 
                NEW.recipient_id::text, 
                COALESCE(NEW.reference_id::text, ''), 
                COALESCE(NEW.source_event, ''),
                EXTRACT(EPOCH FROM NEW.created_at)::text
            ), 'sha256'
        ), 'hex');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 5. Enable RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- 6. Simple Policy (Guest can see their own)
CREATE POLICY "Guests can see their own notifications" ON public.notifications
    FOR SELECT
    USING (
        (recipient_type = 'guest' AND recipient_id IN (
            SELECT id FROM public.guests WHERE user_id = auth.uid()
        ))
        OR
        (recipient_type = 'staff' AND recipient_id = auth.uid())
    );

-- 7. Add updated_at trigger
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_notifications_updated_at
    BEFORE UPDATE ON public.notifications
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();
